---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: Familiarícese con el cobro, el modelo de consumo, los precios y las configuraciones de las licencias basadas en capacidad. 
---
= Obtenga más información sobre las licencias basadas en capacidad para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El sistema de licencias basado en la capacidad de Cloud Volumes ONTAP determina cómo se facturan la capacidad de almacenamiento, los paquetes y los excedentes. Usa esta información para entender el sistema de cobro y el consumo de capacidad, especialmente para las implementaciones en modo estándar.

Las implementaciones en modo privado solo pueden utilizar paquetes Essentials basados en la capacidad en un modelo Bring-Your-Own License (BYOL). Para obtener detalles sobre las licencias para implementaciones en modo privado, consulta link:concept-license-management.html["Conoce Cloud Volumes ONTAP BYOL"^].



[[consumption-models-and-purchase-options]]
== Modelos de consumo y opciones de compra

Los paquetes de licencias basados en capacidad están disponibles con los siguientes modelos de consumo u opciones de compra:

* *Suscripciones del marketplace/contrato anual*: un contrato anual del marketplace de tu proveedor de servicios en la nube. Las implementaciones en modo privado no admiten suscripciones del marketplace.
* *PAYGO*: Una suscripción de pago por uso (PAYGO) es una suscripción por hora del mercado de su proveedor de nube.
* *BYOL*: Bring-Your-Own License (BYOL). Una licencia adquirida a NetApp que puedes usar para desplegar Cloud Volumes ONTAP en cualquier proveedor de cloud.
+

NOTE: NetApp ha restringido la compra, ampliación y renovación de las licencias BYOL, y ha limitado su disponibilidad en escenarios específicos, como en las implementaciones en modo privado. Para más información, consulta https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Disponibilidad restringida de licencias BYOL para Cloud Volumes ONTAP"^].



Tenga en cuenta lo siguiente:

* Si adquieres una licencia BYOL de NetApp, también necesitas suscribirte a la oferta PAYGO en el marketplace de tu proveedor de nube. NetApp ha restringido el modelo de licencia BYOL para las implementaciones en modo estándar. Cuando tu licencia BYOL expire, reemplázala por una suscripción del marketplace de la nube.
+
Su licencia siempre se cobra primero, pero se le cobrará la tarifa por hora del mercado en estos casos:

+
** Si excede su capacidad autorizada
** Si el plazo de su licencia expira


* Si tienes una licencia BYOL y un contrato anual de un marketplace, tu consumo y los excedentes se cobran según la preferencia de facturación que hayas establecido. Para entender cómo se te cobra, consulta link:concept-licensing-charging.html#billing-preferences-and-overages["Preferencias de facturación y excedentes"].
* Sólo se admiten sistemas de nodo único con BYOL en las regiones de China. Las implementaciones en la región de China están exentas de las restricciones de licencia BYOL.




[[how-you-are-charged-for-supported-storage-types-and-packages]]
== Cómo se le cobra por los tipos y paquetes de almacenamiento admitidos

La tarificación en Cloud Volumes ONTAP se basa en una serie de factores, como los paquetes y los tipos de volumen. Los paquetes de licencias basados ​​en capacidad están disponibles con Cloud Volumes ONTAP 9.7 y versiones posteriores.

En los apartados siguientes se explica qué conceptos se cobran, dónde se aplican mínimos y cómo se facturan los excesos.

Para obtener más información sobre los precios, visita la https://bluexp.netapp.com/pricing/["Sitio web de la NetApp Console"^].



[[storage-vms]]
=== Máquinas virtuales de almacenamiento

* No hay costes adicionales de licencia por las máquinas virtuales de almacenamiento (SVM) destinadas al servicio de datos, pero se aplica un cargo mínimo por capacidad de cuatro TiB por cada SVM destinada al servicio de datos.
* Las SVM de recuperación ante desastres se cobran de acuerdo con la capacidad aprovisionada.




[[ha-pairs]]
=== Pares HA

En el caso de los pares HA, solo se cobra por la capacidad aprovisionada en un nodo.  No se le cobrará por los datos que se reflejan de forma sincrónica en el nodo asociado.



[[flexclone-and-flexcache-volumes]]
=== Volúmenes FlexClone y FlexCache

* No se le cobrará por la capacidad utilizada por los volúmenes FlexClone .
* Los volúmenes FlexCache de origen y destino se consideran datos primarios y se cobran según el espacio aprovisionado.




[[readwrite-volumes]]
=== Volúmenes de lectura y escritura

Un volumen grabable (lectura/escritura) es un volumen primario. El sistema cobra la capacidad aprovisionada en función del cargo mínimo por máquina virtual de almacenamiento (SVM). Algunos ejemplos son los volúmenes de lectura/escritura de FlexVol, los volúmenes de auditoría de SnapLock y los volúmenes de auditoría CIFS/NFS. Todos los volúmenes de datos creados por el usuario se cobran según tu suscripción y el tipo de paquete. Los volúmenes internos de ONTAP, como los volúmenes raíz de SVM, no se cobran porque se crean automáticamente y no pueden almacenar datos.



[[essentials-packages]]
=== Paquetes esenciales

El paquete Essentials se factura según el tipo de implementación (HA o nodo único) y el tipo de volumen (primario o secundario). Los precios, de mayor a menor, son _Essentials Primary HA_, _Essentials Primary Single Node_, _Essentials Secondary HA_ y _Essentials Secondary Single Node_. Si compras un contrato en el marketplace o aceptas una oferta privada, el cargo por capacidad es el mismo para cualquier tipo de implementación o volumen.

La licencia se basa completamente en el tipo de volumen creado dentro de los sistemas Cloud Volumes ONTAP :

* Nodo único Essentials: lee y escribe volúmenes creados en un sistema Cloud Volumes ONTAP utilizando un solo nodo ONTAP .
* Essentials HA: volúmenes de lectura y escritura mediante dos nodos ONTAP que pueden conmutarse entre sí para brindar acceso a datos sin interrupciones.
* Nodo único secundario esencial: volúmenes de tipo Protección de datos (DP) (normalmente volúmenes de destino SnapMirror o SnapVault que son de solo lectura) creados en un sistema Cloud Volumes ONTAP utilizando un solo nodo ONTAP .
+

NOTE: Si un volumen de DP de solo lectura pasa a ser un volumen primario, la Console lo trata como datos primarios y calcula los cargos en función del tiempo que el volumen permanezca en modo de lectura/escritura. Si el volumen vuelve a ser de solo lectura, la Console lo trata como datos secundarios y aplica los cargos según la licencia que mejor se ajuste en la Console.

* Elementos esenciales de alta disponibilidad secundaria: volúmenes de tipo protección de datos (DP) (normalmente volúmenes de destino SnapMirror o SnapVault que son de solo lectura) creados en un sistema Cloud Volumes ONTAP mediante dos nodos ONTAP que pueden conmutarse entre sí para brindar acceso a los datos sin interrupciones.




[[minimum-charge]]
== Cargo mínimo

Hay un cargo mínimo de 4 TiB por cada máquina virtual de almacenamiento de servicio de datos que tenga al menos un volumen principal (de lectura y escritura).  Si la suma de los volúmenes principales es menor a 4 TiB, la consola aplica el cargo mínimo de 4 TiB a esa máquina virtual de almacenamiento.

Si aún no ha aprovisionado ningún volumen, no se aplica el cargo mínimo.

Para el paquete Essentials, el cargo de capacidad mínima de 4 TiB no se aplica a las máquinas virtuales de almacenamiento que contienen únicamente volúmenes secundarios (protección de datos). Por ejemplo, si tiene una máquina virtual de almacenamiento con 1 TiB de datos secundarios, se le cobrará solo por ese 1 TiB de datos. Con el tipo de paquete Profesional, la carga de capacidad mínima de 4 TiB se aplica independientemente del tipo de volumen.



[[billing-preferences-and-overages]]
== Preferencias de facturación y excedentes

Podrás elegir cómo quieres que se te cobre en la sección * Licenses and subscriptions* de la Consola. Los excesos ocurren cuando su uso excede la capacidad especificada en su paquete de licencia o suscripción anual.

* * Licencias de NetApp primero *: En este modelo, su uso se cobra primero según la capacidad de su paquete de licencias (BYOL). Si excede la capacidad de su licencia, se cobrarán excedentes según su suscripción anual al mercado o las tarifas por hora a pedido del mercado (PAYGO). Si su licencia BYOL vence, deberá realizar la transición a un modelo de licencia basado en capacidad a través de los mercados en la nube. Para obtener más información, consulte link:task-convert-node-capacity.html["Convertir una licencia basada en nodos de Cloud Volumes ONTAP a una licencia basada en capacidad"].
* *Solo suscripciones al Marketplace*: En este modelo, su uso se carga primero a su suscripción anual al Marketplace. Cualquier uso adicional se cobra según las tarifas por hora bajo demanda del mercado (PAYGO). Cualquier capacidad de licencia no utilizada no se tiene en cuenta para la facturación.


Para obtener más información sobre las preferencias de facturación, consulte https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Obtenga información sobre las preferencias de facturación para licencias y suscripciones."^].



[[how-overages-are-charged-for-essentials-licenses]]
=== Cómo se cobran los excedentes de las licencias Essentials

Si compra una licencia Essentials de NetApp (BYOL) y excede la capacidad autorizada para un paquete Essentials específico, la consola cobra el excedente contra una licencia Essentials de mayor precio (si tiene una con capacidad disponible).  La consola primero utiliza la capacidad disponible que usted pagó antes de cobrar en el mercado.  Si no hay capacidad disponible con su licencia BYOL, la capacidad excedente se cobra a tarifas por hora bajo demanda del mercado (PAYGO) y se agrega a su factura mensual.

Del mismo modo, si dispones de un contrato anual de marketplace o de una oferta privada con varios paquetes Essentials, y tu consumo supera la capacidad comprometida para un tipo específico de implementación y volumen, la Console cobra los excedentes aplicando un paquete Essentials de mayor precio que cuente con capacidad disponible. Una vez agotada esa capacidad, el exceso restante se factura según las tarifas por hora de marketplace bajo demanda (pago por uso) y se añade a tu factura mensual.

Para obtener información sobre la facturación de las licencias de Essentials, consulta <<Paquetes esenciales>>.

He aquí un ejemplo. Digamos que tiene las siguientes licencias para el paquete Essentials:

* Una licencia _Essentials Secondary HA_ de 500 TiB que tiene 500 TiB de capacidad comprometida
* Una licencia _Essentials Single Node_ de 500 TiB que solo tiene 100 TiB de capacidad comprometida


Se aprovisionan otros 50 TiB en un par HA con volúmenes secundarios.  En lugar de cargar esos 50 TiB a PAYGO, la consola cobra el excedente de 50 TiB contra la licencia _Essentials Single Node_.  Esa licencia tiene un precio más alto que _Essentials Secondary HA_, pero utiliza una licencia que ya ha comprado y no agregará costos a su factura mensual.

En *Administración > Licenses and subscriptions*, puedes ver los 50 TiB cobrados contra la licencia _Essentials Single Node_.

He aquí otro ejemplo.  Digamos que tiene las siguientes licencias para el paquete Essentials:

* Una licencia _Essentials Secondary HA_ de 500 TiB que tiene 500 TiB de capacidad comprometida
* Una licencia _Essentials Single Node_ de 500 TiB que solo tiene 100 TiB de capacidad comprometida


Se aprovisionan otros 100 TiB en un par HA con volúmenes primarios.  La licencia que compró no tiene capacidad comprometida _Essentials Primary HA_.  La licencia _Essentials Primary HA_ tiene un precio más alto que las licencias _Essentials Primary Single Node_ y _Essentials Secondary HA_.

En este ejemplo, la consola cobra el excedente a la tarifa del mercado por los 100 TiB adicionales.  Los cargos por exceso aparecerán en su factura mensual.



[[change-license-packages]]
== Cambiar paquetes de licencia

Después de la implementación, puedes cambiar el paquete de un sistema Cloud Volumes ONTAP que use el modelo de licencia basado en capacidad. Por ejemplo, si implementaste un sistema Cloud Volumes ONTAP con el paquete Essentials, puedes cambiarlo al paquete Professional si cambian las necesidades de tu negocio. link:task-manage-capacity-licenses.html["Aprenda a cambiar los métodos de carga"].

NetApp está eliminando progresivamente las licencias por nodo para pasar a las licencias por capacidad. Las licencias por nodo siguen estando disponibles en algunos sistemas más antiguos, como los de los clientes de USPS y las implementaciones en China. Si tienes una licencia por nodo, puedes convertirla en una licencia por capacidad. Para información sobre cómo convertir licencias por nodo en licencias por capacidad, consulta link:task-convert-node-capacity.html["Convertir una licencia basada en nodos a una licencia basada en capacidad"].



[[capacity-limit]]
== Límite de capacidad

En el modelo de licencias basado en capacidad, cada sistema Cloud Volumes ONTAP admite la organización en niveles del almacenamiento de objetos, y la capacidad total en niveles puede escalar hasta el límite de contenedores del proveedor de la nube. Aunque la licencia no impone restricciones de capacidad, siga las https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para garantizar un rendimiento óptimo, confiabilidad y rentabilidad al configurar y administrar la organización en niveles.

Para obtener información sobre los límites de capacidad de cada proveedor de nube, consulte su documentación:

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentación de AWS"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Documentación de Azure para discos administrados"^]y https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Documentación de Azure para el almacenamiento de blobs"^]
* https://cloud.google.com/storage/docs/buckets["Documentación de Google Cloud"^]




[[max-number-of-systems]]
== Número máximo de sistemas

Las licencias basadas en la capacidad limitan cada organización de NetApp Console a 24 sistemas de Cloud Volumes ONTAP. Un _sistema_ puede ser un par HA de Cloud Volumes ONTAP, un sistema de un solo nodo de Cloud Volumes ONTAP o una máquina virtual de almacenamiento adicional que tú crees. La máquina virtual de almacenamiento predeterminada no cuenta para el límite. Este límite se aplica a todos los modelos de licencia.

Por ejemplo, digamos que tienes tres sistemas:

* Un sistema Cloud Volumes ONTAP de un solo nodo con una máquina virtual de almacenamiento (esta es la máquina virtual de almacenamiento predeterminada que se crea cuando se implementa Cloud Volumes ONTAP)
+
Este sistema cuenta como un sistema.

* Un sistema Cloud Volumes ONTAP de un solo nodo con dos máquinas virtuales de almacenamiento (la máquina virtual de almacenamiento predeterminada, más una máquina virtual de almacenamiento adicional que usted creó)
+
Este sistema cuenta como dos sistemas: uno para el sistema de nodo único y uno para la VM de almacenamiento adicional.

* Un par de Cloud Volumes ONTAP HA con tres máquinas virtuales de almacenamiento (la máquina virtual de almacenamiento predeterminada, más dos máquinas virtuales de almacenamiento adicionales que usted creó)
+
Este sistema cuenta como tres sistemas: uno para el par HA y dos para las máquinas virtuales de almacenamiento adicionales.



En total son seis sistemas. De esta forma, dispondría de espacio para 14 sistemas adicionales en su organización.

Si tienes una implementación de gran envergadura que requiere más de 24 sistemas, ponte en contacto con tu representante de cuentas o con el equipo de ventas.

Infórmate sobre los límites de almacenamiento para:

* AWS: link:reference-limits-aws.html["Límites de almacenamiento para Cloud Volumes ONTAP en AWS"]
* Azure: link:reference-limits-azure.html["Límites de almacenamiento para Cloud Volumes ONTAP en Azure"]
* Google Cloud: link:reference-limits-gcp.html["Límites de almacenamiento para Cloud Volumes ONTAP en Google Cloud"]


.Enlaces relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Licencias para Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["Administrar licencias basadas en capacidad para Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html["Gestiona las licencias por nodo"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-convert-node-capacity.html["Convertir una licencia basada en nodos a una licencia basada en capacidad"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-keystone.html["Administrar suscripciones de Keystone"^]

