---
sidebar: sidebar 
permalink: reference-default-configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Comprender cómo se configura Cloud Volumes ONTAP de manera predeterminada puede ayudarlo a configurar y administrar sus sistemas, especialmente si está familiarizado con ONTAP porque la configuración predeterminada de Cloud Volumes ONTAP es diferente a la de ONTAP. 
---
= Configuraciones predeterminadas compatibles con Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comprender cómo se configura Cloud Volumes ONTAP de manera predeterminada puede ayudarlo a configurar y administrar sus sistemas, especialmente si está familiarizado con ONTAP porque la configuración predeterminada de Cloud Volumes ONTAP es diferente a la de ONTAP.



== Configuración predeterminada

* La consola de NetApp crea una máquina virtual de almacenamiento que sirve datos cuando implementa Cloud Volumes ONTAP.  Algunas configuraciones admiten máquinas virtuales de almacenamiento adicionales. link:task-managing-svms.html["Obtenga más información sobre la gestión de máquinas virtuales de almacenamiento"] .
+
A partir de la versión 3.9.5, los informes de espacio lógico están habilitados en la máquina virtual de almacenamiento inicial.  Cuando el espacio se informa de manera lógica, ONTAP informa el espacio del volumen de modo que todo el espacio físico ahorrado por las funciones de eficiencia de almacenamiento también se informa como utilizado.  Para obtener información sobre las funciones de eficiencia del almacenamiento en línea, consulte el artículo de la base de conocimientos https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/What_Inline_Storage_Efficiency_features_are_supported_with_CVO#["KB: ¿Qué funciones de eficiencia de almacenamiento en línea son compatibles con CVO?"^]

* La consola instala automáticamente las siguientes licencias de funciones de ONTAP en Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** iSCSI
** Administración de claves de cifrado multiinquilino (MTEKM), a partir de Cloud Volumes ONTAP 9.12.1 GA
** Cifrado de volumen de NetApp (solo para sistemas BYOL (trae tu propia licencia) o sistemas de pago por uso registrados (PAYGO))
** NFS ifdef::aws[] endif::aws[] ifdef::azure[] endif::azure[]
** SnapMirror
** SnapRestore
** SnapVault


* Se crean varias interfaces de red de forma predeterminada:
+
** Un LIF de gestión de clústeres
** Un LIF entre clústeres




ifdef::azure[]

* Un LIF de administración de SVM en sistemas de alta disponibilidad en Azure


endif::azure[]

ifdef::gcp[]

* Un LIF de gestión de SVM en sistemas HA en Google Cloud


endif::gcp[]

ifdef::aws[]

* Un LIF de gestión de SVM en sistemas de nodo único en AWS


endif::aws[]

* Un LIF de gestión de nodos


ifdef::gcp[]

+ En Google Cloud, este LIF se combina con el LIF entre clústeres.

endif::gcp[]

* Un LIF de datos iSCSI
* Un LIF de datos CIFS y NFS
+

NOTE: La conmutación por error de LIF está deshabilitada de forma predeterminada para Cloud Volumes ONTAP debido a los requisitos del proveedor de la nube.  Migrar un LIF a un puerto diferente rompe la asignación externa entre direcciones IP e interfaces de red en la instancia, lo que hace que el LIF sea inaccesible.

+
** Cloud Volumes ONTAP envía copias de seguridad de configuración al agente de la consola mediante HTTP.
+
Se puede acceder a las copias de seguridad desde \http://ipaddress/occm/offboxconfig/ donde _ipaddress_ es la dirección IP del host del agente de la consola.

+
Puede utilizar las copias de seguridad para reconfigurar su sistema Cloud Volumes ONTAP .  Para obtener más información sobre las copias de seguridad de configuración, consulte la https://docs.netapp.com/us-en/ontap/system-admin/config-backup-file-concept.html["Documentación de ONTAP"^] .

** La consola establece algunos atributos de volumen de manera diferente a otras herramientas de administración (ONTAP System Manager o ONTAP CLI, por ejemplo).
+
La siguiente tabla enumera los atributos de volumen configurados de forma diferente a los predeterminados:

+
[cols="15,85"]
|===
| Atributo | Valor que configura la consola 


| Modo de tamaño automático | crecer 


| Tamaño automático máximo  a| 
1.000 por ciento


NOTE: El administrador de la organización o de la cuenta puede modificar este valor desde la página de Configuración.



| Estilo de seguridad | NTFS para volúmenes CIFS UNIX para volúmenes NFS 


| Estilo de garantía de espacio | ninguna 


| Permisos UNIX (solo NFS) | 777 
|===
+
Para obtener información sobre estos atributos, consultelink:https://docs.netapp.com/us-en/ontap-cli-9121/volume-create.html["Página de manual de ONTAP _volume create_"] .







== Discos internos para datos del sistema

Además del almacenamiento para los datos del usuario, la Consola también compra almacenamiento en la nube para los datos del sistema.

ifdef::aws[]



=== AWS

* Tres discos por nodo para datos de arranque, raíz y núcleo:
+
** Disco io1 de 47 GiB para datos de arranque
** Disco gp3 de 140 GiB para datos raíz
** Disco gp2 de 540 GiB para datos centrales


* Para pares HA:
+
** Dos volúmenes EBS st1 para la instancia del mediador, uno de aproximadamente 8 GiB como disco raíz y uno de 4 GiB como disco de datos
** Un disco gp3 de 140 GiB en cada nodo para contener una copia de los datos raíz del otro nodo
+

NOTE: En algunas zonas, el tipo de disco EBS disponible solo puede ser gp2.



* Una instantánea de EBS para cada disco de arranque y disco raíz
+

NOTE: Las instantáneas se crean automáticamente al reiniciar.

* Cuando habilita el cifrado de datos en AWS mediante el Servicio de administración de claves (KMS), los discos de arranque y raíz de Cloud Volumes ONTAP también se cifran.  Esto incluye el disco de arranque para la instancia del mediador en un par HA.  Los discos se cifran mediante la CMK que selecciona cuando agrega un sistema Cloud Volumes ONTAP .



TIP: En AWS, la NVRAM está en el disco de arranque.

endif::aws[]

ifdef::azure[]



=== Azure (nodo único)

* Tres discos SSD Premium:
+
** Un disco de 10 GiB para datos de arranque
** Un disco de 140 GiB para datos raíz
** Un disco de 512 GiB para NVRAM
+
Si la máquina virtual que eligió para Cloud Volumes ONTAP admite SSD Ultra, entonces el sistema utiliza un SSD Ultra de 32 GiB para NVRAM, en lugar de un SSD Premium.



* Un disco duro HDD estándar de 1024 GiB para guardar núcleos
* Una instantánea de Azure para cada disco de arranque y disco raíz
* De forma predeterminada, cada disco en Azure está cifrado en reposo.
+
Si la máquina virtual que eligió para Cloud Volumes ONTAP admite discos administrados Premium SSD v2 como discos de datos, el sistema utiliza un disco administrado Premium SSD v2 de 32 GiB para NVRAM y otro como disco raíz.





=== Azure (par HA)

.Pares de HA con blob de página
* Dos discos SSD Premium de 10 GiB para el volumen de arranque (uno por nodo)
* Dos blobs de páginas de almacenamiento premium de 140 GiB para el volumen raíz (uno por nodo)
* Dos discos HDD estándar de 1024 GiB para guardar núcleos (uno por nodo)
* Dos discos SSD Premium de 512 GiB para NVRAM (uno por nodo)
* Una instantánea de Azure para cada disco de arranque y disco raíz
+

NOTE: Las instantáneas se crean automáticamente al reiniciar.

* De forma predeterminada, cada disco en Azure está cifrado en reposo.


.Pares de alta disponibilidad con discos administrados compartidos en múltiples zonas de disponibilidad
* Dos discos SSD Premium de 10 GiB para el volumen de arranque (uno por nodo)
* Dos discos SSD Premium de 512 GiB para el volumen raíz (uno por nodo)
* Dos discos HDD estándar de 1024 GiB para guardar núcleos (uno por nodo)
* Dos discos SSD Premium de 512 GiB para NVRAM (uno por nodo)
* Una instantánea de Azure para cada disco de arranque y disco raíz
+

NOTE: Las instantáneas se crean automáticamente al reiniciar.

* De forma predeterminada, cada disco en Azure está cifrado en reposo.


.Pares de alta disponibilidad con discos administrados compartidos en zonas de disponibilidad única
* Dos discos SSD Premium de 10 GiB para el volumen de arranque (uno por nodo)
* Dos discos administrados compartidos SSD Premium de 512 GiB para el volumen raíz (uno por nodo)
* Dos discos HDD estándar de 1024 GiB para guardar núcleos (uno por nodo)
* Dos discos administrados SSD Premium de 512 GiB para NVRAM (uno por nodo)


Si su máquina virtual admite discos administrados Premium SSD v2 como discos de datos, utiliza discos administrados Premium SSD v2 de 32 GiB para NVRAM y discos administrados compartidos Premium SSD v2 de 512 GiB para el volumen raíz.

Puede implementar pares de alta disponibilidad en una única zona de disponibilidad y utilizar discos administrados Premium SSD v2 cuando se cumplan las siguientes condiciones:

* La versión de Cloud Volumes ONTAP es 9.15.1 o posterior.
* La región y la zona seleccionadas admiten discos administrados Premium SSD v2.  Para obtener información sobre las regiones admitidas, consulte https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Sitio web de Microsoft Azure: Productos disponibles por región"^] .
* La suscripción está registrada para Microsoftlink:task-saz-feature.html["Característica Microsoft.Compute/VMOrchestratorZonalMultiFD"] .


endif::azure[]

ifdef::gcp[]



=== Google Cloud (nodo único)

* Un disco persistente SSD de 10 GiB para datos de arranque
* Un disco persistente SSD de 64 GiB para datos raíz
* Un disco persistente SSD de 500 GiB para NVRAM
* Un disco persistente estándar de 315 GiB para guardar núcleos
* Instantáneas de datos de arranque y raíz
+

NOTE: Las instantáneas se crean automáticamente al reiniciar.

* Los discos de arranque y raíz están cifrados de forma predeterminada.




=== Google Cloud (par HA)

* Dos discos persistentes SSD de 10 GiB para datos de arranque
* Cuatro discos persistentes SSD de 64 GiB para datos raíz
* Dos discos persistentes SSD de 500 GiB para NVRAM
* Dos discos persistentes estándar de 315 GiB para guardar núcleos
* Un disco persistente estándar de 10 GiB para datos del mediador
* Un disco persistente estándar de 10 GiB para datos de arranque del mediador
* Instantáneas de datos de arranque y raíz
+

NOTE: Las instantáneas se crean automáticamente al reiniciar.

* Los discos de arranque y raíz están cifrados de forma predeterminada.


endif::gcp[]



=== Dónde residen los discos

Disposición del almacenamiento:

* Los datos de arranque residen en un disco conectado a la instancia o máquina virtual.
+
Este disco, que contiene la imagen de arranque, no está disponible para Cloud Volumes ONTAP.

* Los datos raíz, que contienen la configuración del sistema y los registros, residen en aggr0.
* El volumen raíz de la máquina virtual de almacenamiento (SVM) reside en aggr1.
* Los volúmenes de datos también residen en aggr1.

