---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en AWS para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configures tu sistema con los valores máximos. 
---
= Límites de almacenamiento para Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configures tu sistema con los valores máximos.



[[maximum-system-capacity-by-license]]
== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema incluye el almacenamiento basado en disco más el almacenamiento de objetos usado para la organización de datos por niveles.

NetApp no admite superar el límite de capacidad del sistema. Si alcanzas el límite de capacidad autorizada, la NetApp Console muestra un mensaje de acción requerida y ya no te permite añadir discos adicionales.

Para algunas configuraciones, los límites de disco te impiden alcanzar el límite de capacidad usando solo discos. En esos casos, puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^]. Consulta los límites de capacidad y de disco a continuación para más detalles.

[[cap-license-aws]]
.Límite de capacidad para licencias basadas en capacidad
Con las licencias basadas en la capacidad, cada sistema Cloud Volumes ONTAP admite el almacenamiento por niveles en el almacenamiento de objetos. La capacidad total por niveles puede escalar hasta el límite de bucket del proveedor de la nube. Aunque la licencia no impone restricciones de capacidad, deberías seguir las  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para asegurar un rendimiento, fiabilidad y rentabilidad óptimos al configurar y gestionar el almacenamiento por niveles. Consulta la  https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentación de AWS"^] para más información.

Límites de capacidad para otros tipos de licencia::


[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GiB 


| PAYGO Explore | 2 TiB (no se admite el escalonamiento de datos con Explore) 


| PAYGO Standard | 10 TiB 


| PAYGO Premium | 368 TiB 


| Licencia basada en nodos | 2 PiB (requiere varias licencias) 
|===
.Para HA, ¿el límite de capacidad de la licencia es por nodo o para todo el sistema de parejas de alta disponibilidad?
El límite de capacidad es para todo el sistema de parejas de alta disponibilidad. No es por nodo. Por ejemplo, la licencia Premium permite hasta 368 TiB en ambos nodos.

.Para un sistema de HA en AWS, ¿los datos reflejados cuentan contra el límite de capacidad?
No, no es así. Los datos en un sistema de parejas de alta disponibilidad de AWS se reflejan de forma sincrónica entre los nodos para que los datos estén disponibles en caso de fallo. Por ejemplo, si compras un disco de 8 TiB en el nodo A, la Console también asigna un disco de 8 TiB en el nodo B que se usa para los datos reflejados. Aunque se aprovisionaron 16 TiB de capacidad, solo 8 TiB cuentan para el límite de licencia.



[[aggregate-limits]]
== Límites de agregados

Cloud Volumes ONTAP utiliza volúmenes EBS como discos y los agrupa en _aggregates_. Los agregados proporcionan almacenamiento a los volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados | Nodo único: igual que el límite de discos Pares de HA: 18 en un nodo ^1^ 


| Tamaño máximo del agregado ^2^  a| 
* 96 TiB de capacidad bruta
* 128 TiB de capacidad bruta con Elastic Volumes ^3^




| Discos por agregado ^4^  a| 
* 1-6
* 4 u 8 con Elastic Volumes ^3^




| Número máximo de grupos RAID por agregado | 2 
|===
Notas:

. No puedes crear 18 agregados en ambos nodos de un sistema de parejas de alta disponibilidad porque eso excedería el límite de discos de datos.
. El tamaño máximo del agregado depende de sus discos y no incluye el almacenamiento de objetos que usas para la organización de datos por niveles.
. Si tienes una configuración que admite la función Amazon EBS Elastic Volumes, entonces un agregado puede contener hasta 8 discos, lo que proporciona hasta 128 TiB de capacidad. Por defecto, Cloud Volumes ONTAP 9.11.0 y versiones posteriores tienen Amazon EBS Elastic Volumes habilitado cuando usas discos gp3 o io1. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Obtenga más información sobre la compatibilidad con Elastic Volumes"^]
. Todos los discos de un agregado deben tener el mismo tamaño.




[[disk-and-tiering-limits-by-ec2-instance]]
== Límites de discos y niveles por instancia EC2

Los límites de capacidad varían en función de la familia de tipos de instancia EC2 que usas y de si usas un sistema de nodo único o un par de HA.

Las siguientes notas te dan detalles sobre los números que verás en las tablas de abajo:

* Los límites de los discos son específicos de los discos que contienen datos de usuario.
+
Los límites no incluyen el disco de arranque ni el disco raíz.

* Se indica una capacidad máxima del sistema cuando se usan solo discos y cuando se usan discos y la organización por niveles de datos en frío al almacenamiento de objetos.
* Cloud Volumes ONTAP utiliza volúmenes EBS como discos, con un tamaño máximo de disco de 16 TiB.




[[limits-for-different-deployment-modes-of-capacity-based-licensing]]
=== Límites para los diferentes modos de implementación del licenciamiento basado en capacidad

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que usan un paquete de licencias basado en capacidad. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Conoce las opciones de licencia de Cloud Volumes ONTAP"^]


NOTE: Para conocer la capacidad máxima del sistema y los límites de capacidad de los niveles de datos para configuraciones de nodo único y HA, consulta <<cap-license-aws>>.



==== Nodo único

[cols="18,18,32,width=100%,options="]
|===


| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos 


| instancias c5, m5 y r5 | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304 TiB 
|===
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== Pares HA

[cols="18,18,32,width=100%,options="]
|===


| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos 


| instancias c5, m5 y r5 | 18 | 288 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^1^ | 256 TiB 
|===
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




[[limits-for-different-deployment-modes-of-node-based-licensing]]
=== Límites para los diferentes modos de implementación de licencias basadas en nodos

Los siguientes límites de disco se aplican a los sistemas Cloud Volumes ONTAP que utilizan licencias basadas en nodo, que es el modelo de licencia de la generación anterior que permitía licenciar Cloud Volumes ONTAP por nodo. La licencia basada en nodo sigue disponible para los clientes existentes.

Puedes adquirir varias licencias basadas en nodos para un Cloud Volumes ONTAP BYOL de nodo único o un sistema de parejas de alta disponibilidad para asignar más de 368 TiB de capacidad, hasta el límite máximo probado y soportado de capacidad del sistema de 2 PiB. Ten en cuenta que los límites de disco pueden impedirte alcanzar el límite de capacidad usando solo discos. Puedes ir más allá del límite de disco mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^]. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Aprende cómo añadir licencias de sistema adicionales a Cloud Volumes ONTAP"^]. Aunque Cloud Volumes ONTAP soporta hasta el límite máximo de capacidad del sistema probado y soportado de 2 PiB, cruzar el límite de 2 PiB resulta en una configuración del sistema no soportada.

Las regiones de AWS Secret Cloud y Top Secret Cloud admiten compras de varias licencias basadas en nodos a partir de Cloud Volumes ONTAP 9.12.1.



==== Nodo único con PAYGO Premium

[cols="18,18,32,32"]
|===
| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y organización en niveles de datos 


| instancias c5, m5 y r5 | 21 ^1^ | 336 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB 
|===
. 21 discos de datos es el límite para _nuevas_ implementaciones de Cloud Volumes ONTAP. Si actualizas un sistema que fue creado con la versión 9.7 o anterior, entonces el sistema sigue soportando 22 discos. Se soporta un disco de datos menos en los nuevos sistemas que usan estos tipos de instancia porque se añadió un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== Nodo único con BYOL

[cols="18,18,16,16,16,16"]
|===
| Instancia | Máximo de discos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + data tiering* | *Solo discos* | *Discos + data tiering* 


| instancias c5, m5 y r5 | 21 ^1^ | 336 TiB | 368 TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^2^ | 304 TiB | 368 TiB | 304 TiB | 2 PiB 
|===
. 21 discos de datos es el límite para _nuevas_ implementaciones de Cloud Volumes ONTAP. Si actualizas un sistema que fue creado con la versión 9.7 o anterior, entonces el sistema sigue soportando 22 discos. Se soporta un disco de datos menos en los nuevos sistemas que usan estos tipos de instancia porque se añadió un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== Pares de alta disponibilidad con PAYGO Premium

[cols="18,18,32,32"]
|===
| Instancia | Máximo de discos por nodo | Capacidad máxima del sistema solo con discos | Capacidad máxima del sistema con discos y organización en niveles de datos 


| instancias c5, m5 y r5 | 18 ^1^ | 288 TiB | 368 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB 
|===
. 18 discos de datos es el límite para _nuevas_ implementaciones de Cloud Volumes ONTAP. Si actualizas un sistema que fue creado con la versión 9.7 o anterior, entonces el sistema sigue soportando 19 discos. Se soporta un disco de datos menos en los nuevos sistemas que usan estos tipos de instancia porque se añadió un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




==== Pares de HA con BYOL

[cols="18,18,16,16,16,16"]
|===
| Instancia | Máximo de discos por nodo 2+| Capacidad máxima del sistema con una licencia 2+| Capacidad máxima del sistema con varias licencias 


2+|  | *Solo discos* | *Discos + data tiering* | *Solo discos* | *Discos + data tiering* 


| instancias c5, m5 y r5 | 18 ^1^ | 288 TiB | 368 TiB | 288 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16 ^2^ | 256 TiB | 368 TiB | 256 TiB | 2 PiB 
|===
. 18 discos de datos es el límite para _nuevas_ implementaciones de Cloud Volumes ONTAP. Si actualizas un sistema que fue creado con la versión 9.7 o anterior, entonces el sistema sigue soportando 19 discos. Se soporta un disco de datos menos en los nuevos sistemas que usan estos tipos de instancia porque se añadió un disco central a partir de la versión 9.8.
. Este tipo de instancia tiene más discos NVMe locales que otros tipos de instancia, lo que significa que se admite una menor cantidad de discos de datos.




[[storage-vm-limits]]
== Límites de las máquinas virtuales de almacenamiento

Algunas configuraciones te permiten crear VMs de almacenamiento adicionales (SVMs) para Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["Aprende cómo crear máquinas virtuales de almacenamiento adicionales"^].

[cols="40,60"]
|===
| Tipo de licencia | Límite de Storage VM 


| *Freemium*  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *PAYGO basado en capacidad o BYOL* ^3^  a| 
24 máquinas virtuales de almacenamiento en total ^1,2^



| *PAYGO basado en nodos*  a| 
* 1 VM de almacenamiento para servir datos
* 1 máquina virtual de almacenamiento para recuperación ante desastres




| *BYOL basado en nodos* ^4^  a| 
* 24 máquinas virtuales de almacenamiento en total ^1,2^


|===
. El límite puede ser inferior, dependiendo del tipo de instancia EC2 que uses. Los límites por instancia se enumeran en la sección siguiente.
. Estas 24 máquinas virtuales de almacenamiento pueden servir datos o configurarse para la recuperación ante desastres (DR).
. En el caso de las licencias basadas en la capacidad, no hay costes adicionales de licencia para las máquinas virtuales de almacenamiento adicionales, pero hay un cargo mínimo de 4 TiB de capacidad por máquina virtual de almacenamiento. Por ejemplo, si creas dos máquinas virtuales de almacenamiento y cada una tiene 2 TiB de capacidad aprovisionada, se te cobrará un total de 8 TiB.
. Para BYOL basado en nodos, se requiere una licencia add-on para cada VM de almacenamiento _data-serving_ adicional más allá de la primera VM de almacenamiento que viene por defecto con Cloud Volumes ONTAP. Contacta a tu equipo de cuenta para obtener una licencia add-on de VM de almacenamiento.
+
Las máquinas virtuales de almacenamiento que configuras para la recuperación ante desastres (DR) no requieren una licencia adicional (son gratuitas), pero sí cuentan para el límite de máquinas virtuales de almacenamiento. Por ejemplo, si tienes 12 máquinas virtuales de almacenamiento que sirven datos y 12 máquinas virtuales de almacenamiento configuradas para la recuperación ante desastres, entonces has alcanzado el límite y no puedes crear ninguna máquina virtual de almacenamiento adicional.





[[storage-vm-limit-by-ec2-instance-type]]
=== Límite de Storage VM por tipo de instancia EC2

Cuando creas una VM de almacenamiento adicional, necesitas asignar direcciones IP privadas al puerto e0a. La tabla a continuación identifica el número máximo de IP privadas por interfaz, así como el número de direcciones IP que están disponibles en el puerto e0a después de que Cloud Volumes ONTAP ha sido desplegado. El número de direcciones IP disponibles afecta directamente el número máximo de VM de almacenamiento para esa configuración.

Las instancias enumeradas a continuación son para las familias de instancias c5, m5 y r5.

[cols="6*"]
|===
| Configuración | Tipo de instancia | IPs privadas máximas por interfaz | IPs restantes después del despliegue ^1^ | Máximo de VMs de almacenamiento sin una mgmt LIF ^2,3^ | Máximo de VMs de almacenamiento con una mgmt LIF ^2,3^ 


.9+| *Nodo único* | *.xlarge | 15 | 9 | 10 | 5 


| *.2xlarge | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *Par HA en una sola AZ* | *.xlarge | 15 | 10 | 11 | 5 


| *.2xlarge | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *Par de HA en varias AZ* | *.xlarge | 15 | 12 | 13 | 13 


| *.2xlarge | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. Este número indica cuántas direcciones IP privadas _restantes_ hay disponibles en el puerto e0a después de desplegar y configurar Cloud Volumes ONTAP. Por ejemplo, un sistema *.2xlarge admite un máximo de 15 direcciones IP por interfaz de red. Cuando se despliega un par de HA en una sola AZ, se asignan 5 direcciones IP privadas al puerto e0a. Como resultado, un par de HA que usa un tipo de instancia *.2xlarge tiene 10 direcciones IP privadas restantes para máquinas virtuales de almacenamiento adicionales.
. El número listado en estas columnas incluye la VM de almacenamiento inicial que la NetApp Console crea por defecto. Por ejemplo, si 24 aparece en esta columna, significa que puedes crear 23 VM de almacenamiento adicionales para un total de 24.
. Una LIF de gestión para la VM de almacenamiento es opcional. Una LIF de gestión proporciona una conexión a herramientas de gestión como SnapCenter.
+
Dado que requiere una dirección IP privada, limitará el número de máquinas virtuales de almacenamiento adicionales que puedes crear. La única excepción es un par de HA en varias AZ. En ese caso, la dirección IP para el LIF de gestión es una dirección IP _flotante_, así que no cuenta para el límite de IP _privada_.





[[file-and-volume-limits]]
== Límites de archivos y volúmenes

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


.2+| *Archivos* | Tamaño máximo ^2^ | 128 TB 


| Máximo por volumen | Dependiente del tamaño del volumen, hasta 2 mil millones 


| *Volúmenes FlexClone* | Profundidad de clonación jerárquica ^1^ | 499 


.3+| *volúmenes FlexVol* | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo ^3^ | 300 TiB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Copias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
. La profundidad jerárquica de clones es la profundidad máxima de una jerarquía anidada de FlexClone volúmenes que se pueden crear a partir de un solo FlexVol volumen.
. A partir de ONTAP 9.12.1P2, el límite es 128 TB. En ONTAP 9.11.1 y versiones anteriores, el límite es 16 TB.
. La creación de volúmenes FlexVol de hasta un tamaño máximo de 300 TiB es compatible usando las siguientes herramientas y versiones mínimas:
+
** System Manager y la CLI de ONTAP desde Cloud Volumes ONTAP 9.12.1 P2 y 9.13.0 P2
** A partir de Cloud Volumes ONTAP 9.13.1






[[iscsi-storage-limits]]
== límites de almacenamiento iSCSI

[cols="3*"]
|===
| almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamaño máximo | 16 TiB 


| Máximo por volumen | 512 


| *igroups* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *sesiones iSCSI* | Máximo por nodo | 1.024 


.2+| *LIF* | Máximo por puerto | 32 


| Máximo por conjunto de puertos | 32 


| *portset* | Máximo por nodo | 256 
|===