---
sidebar: sidebar 
permalink: reference-versions.html 
keywords: versions, supported versions, new versions, cloud volumes ontap version 
summary: La NetApp Console le permite elegir entre varias versiones diferentes de ONTAP cuando crea un nuevo sistema Cloud Volumes ONTAP . 
---
= Versiones de ONTAP compatibles con implementaciones de Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console le permite elegir entre varias versiones diferentes de ONTAP cuando agrega un sistema Cloud Volumes ONTAP .

Las versiones de Cloud Volumes ONTAP distintas de las enumeradas aquí no están disponibles para nuevas implementaciones. El parche o la versión genérica (General Availability) en una versión aquí representa la versión base disponible para la implementación. Para detalles sobre los parches disponibles, consulta el  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html["notas de la versión con control de versiones"^] de cada versión.

Para información sobre la actualización, consulta link:task-updating-ontap-cloud.html#supported-upgrade-paths["Rutas de actualización admitidas"].

ifdef::aws[]



== AWS

Nodo único::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5
* 9.5 P6


--
par HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5
* 9.5 P6


--


endif::aws[]

ifdef::azure[]



== Azur

Nodo único::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--
par HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--


endif::azure[]

ifdef::gcp[]



== Google Cloud

Nodo único::
+
--
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5


--
par HA::
+
--
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8


--


endif::gcp[]
