---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP tiene límites de configuración de almacenamiento en Google Cloud para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configures tu sistema con los valores máximos. 
---
= Límites de almacenamiento para Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP tiene límites de configuración de almacenamiento para proporcionar operaciones fiables. Para obtener el mejor rendimiento, no configures tu sistema con los valores máximos.



[[maximum-system-capacity-by-license]]
== Capacidad máxima del sistema por licencia

La capacidad máxima del sistema para un sistema Cloud Volumes ONTAP está determinada por su licencia. La capacidad máxima del sistema incluye el almacenamiento basado en disco más el almacenamiento de objetos usado para la organización de datos por niveles.

NetApp no admite superar el límite de capacidad del sistema. Si alcanzas el límite de capacidad autorizada, la NetApp Console muestra un mensaje de acción requerida y ya no te permite añadir discos adicionales.

Para algunas configuraciones, los límites de disco te impiden alcanzar el límite de capacidad usando solo discos. Puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["Agrupación de datos inactivos en niveles de almacenamiento de objetos"^]. Consulta los límites de disco a continuación para más detalles.

[[cap-license-gcp]]
.Límite de capacidad para licencias basadas en capacidad
Con las licencias basadas en la capacidad, cada sistema Cloud Volumes ONTAP admite el almacenamiento por niveles en el almacenamiento de objetos. La capacidad total por niveles puede escalar hasta el límite de bucket del proveedor de la nube. Aunque la licencia no impone restricciones de capacidad, deberías seguir las  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Mejores prácticas de FabricPool"^] para asegurar un rendimiento, fiabilidad y rentabilidad óptimos al configurar y gestionar el almacenamiento por niveles. Consulta la  https://cloud.google.com/storage/docs/buckets["Documentación de Google Cloud"^] para más información.

Límites de capacidad para otros tipos de licencia::


[cols="25,75"]
|===
| Licencia | Capacidad máxima del sistema (discos + almacenamiento de objetos) 


| Freemium | 500 GB 


| PAYGO Explore | 2 TB (el escalonamiento de datos no es compatible con Explore) 


| PAYGO Standard | 10 TB 


| PAYGO Premium | 368 TB 


| Licencia basada en nodos | 2 PiB (requiere varias licencias) 
|===
.Para un sistema de parejas de alta disponibilidad, ¿el límite de capacidad con licencia es por nodo o para todo el sistema de parejas de alta disponibilidad?
El límite de capacidad es para todo el sistema de parejas de alta disponibilidad. No es por nodo. Por ejemplo, si usas la licencia Premium, puedes tener hasta 368 TB de capacidad entre ambos nodos.

.Para un sistema de parejas de alta disponibilidad, ¿los datos reflejados cuentan para el límite de capacidad con licencia?
No, no es así. Los datos en un sistema de parejas de alta disponibilidad se reflejan de forma sincrónica entre los nodos para que los datos estén disponibles en caso de fallo en Google Cloud. Por ejemplo, si compras un disco de 8 TB en el nodo A, la Console también asigna un disco de 8 TB en el nodo B que se usa para los datos reflejados. Aunque se configuran 16 TB de capacidad, solo 8 TB cuentan para el límite de la licencia.



[[aggregate-limits]]
== Límites de agregados

Cloud Volumes ONTAP agrupa los discos de Google Cloud Platform en _agregados_. Los agregados proporcionan almacenamiento a los volúmenes.

[cols="2*"]
|===
| Parámetro | Límite 


| Número máximo de agregados de datos ^1^  a| 
* 99 para un solo nodo
* 64 para todo un sistema de parejas de alta disponibilidad




| Tamaño máximo del agregado | 256 TB de capacidad bruta ^2^ 


| Discos por agregado | 1-6 ^3^ 


| Número máximo de grupos RAID por agregado | 1 
|===
Notas:

. El número máximo de agregados de datos no incluye el agregado raíz.
. Los discos que componen el agregado determinan el límite de capacidad del agregado. Este límite no incluye el almacenamiento de objetos utilizado para la organización de datos por niveles.
. Todos los discos de un agregado deben tener el mismo tamaño.




[[disk-and-tiering-limits]]
== Límites de discos y niveles

La siguiente tabla muestra la capacidad máxima del sistema solo con discos, y con discos y la organización por niveles de datos en frío en el almacenamiento de objetos. Los límites de los discos son específicos de los discos que contienen datos de usuario. Los límites no incluyen el disco de arranque, el disco raíz ni la NVRAM.

[cols="60,40"]
|===
| Parámetro | Límite 


| Máximo de discos de datos  a| 
* 124 para sistemas de un solo nodo
* 123 por nodo para sistema de parejas de alta disponibilidad




| Tamaño máximo del disco | 64 TB 


| Capacidad máxima del sistema solo con discos | 256 TB ^1^ 


| Capacidad máxima del sistema con discos y organización de datos en frío en un bucket de Google Cloud Storage | Depende de la licencia. Consulta los límites máximos de capacidad del sistema más arriba. 
|===
^1^ Este límite está definido por los límites de las máquinas virtuales en Google Cloud Platform.



[[storage-vm-limits]]
== Límites de las máquinas virtuales de almacenamiento

Algunas configuraciones te permiten crear VMs de almacenamiento adicionales (SVMs) para Cloud Volumes ONTAP.

Estos son los límites probados. Configurar más máquinas virtuales de almacenamiento no es compatible.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Aprende cómo crear máquinas virtuales de almacenamiento adicionales"^].

[cols="2*"]
|===
| Tipo de licencia | Límite de Storage VM 


| *Freemium*  a| 
24 máquinas virtuales de almacenamiento en total ^1^



| *PAYGO basado en capacidad o BYOL* ^2^  a| 
24 máquinas virtuales de almacenamiento en total ^1^



| *BYOL basado en nodos* ^3^  a| 
24 máquinas virtuales de almacenamiento en total ^1^



| *PAYGO basado en nodos*  a| 
* 1 VM de almacenamiento para servir datos
* 1 máquina virtual de almacenamiento para recuperación ante desastres


|===
. Estas 24 máquinas virtuales de almacenamiento pueden servir datos o configurarse para la recuperación ante desastres (DR).
. En el caso de las licencias basadas en la capacidad, no hay costes adicionales de licencia para las máquinas virtuales de almacenamiento adicionales, pero hay un cargo mínimo de 4 TiB de capacidad por máquina virtual de almacenamiento. Por ejemplo, si creas dos máquinas virtuales de almacenamiento y cada una tiene 2 TiB de capacidad aprovisionada, se te cobrará un total de 8 TiB.
. Para BYOL basado en nodos, se requiere una licencia add-on para cada VM de almacenamiento _data-serving_ adicional más allá de la primera VM de almacenamiento que viene por defecto con Cloud Volumes ONTAP. Contacta a tu equipo de cuenta para obtener una licencia add-on de VM de almacenamiento.
+
Las máquinas virtuales de almacenamiento que configuras para la recuperación ante desastres (DR) no requieren una licencia adicional (son gratuitas), pero sí cuentan para el límite de máquinas virtuales de almacenamiento. Por ejemplo, si tienes 12 máquinas virtuales de almacenamiento que sirven datos y 12 máquinas virtuales de almacenamiento configuradas para la recuperación ante desastres, entonces has alcanzado el límite y no puedes crear ninguna máquina virtual de almacenamiento adicional.





[[logical-storage-limits]]
== Límites lógicos de almacenamiento

[cols="22,22,56"]
|===
| Almacenamiento lógico | Parámetro | Límite 


.2+| *Archivos* | Tamaño máximo ^2^ | 128 TB 


| Máximo por volumen | Dependiente del tamaño del volumen, hasta 2 mil millones 


| *Volúmenes FlexClone* | Profundidad de clonación jerárquica ^12^ | 499 


.3+| *volúmenes FlexVol* | Máximo por nodo | 500 


| Tamaño mínimo | 20 MB 


| Tamaño máximo ^3^ | 300 TiB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Copias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
. La profundidad jerárquica de clones es la profundidad máxima de una jerarquía anidada de FlexClone volúmenes que se pueden crear a partir de un solo FlexVol volumen.
. A partir de ONTAP 9.12.1P2, el límite es 128 TB. En ONTAP 9.11.1 y versiones anteriores, el límite es 16 TB.
. La creación de volúmenes FlexVol de hasta un tamaño máximo de 300 TiB es compatible usando las siguientes herramientas y versiones mínimas:
+
** System Manager y la ONTAP CLI a partir de Cloud Volumes ONTAP 9.12.1 P2 y 9.13.0 P2
** A partir de Cloud Volumes ONTAP 9.13.1






[[iscsi-storage-limits]]
== límites de almacenamiento iSCSI

[cols="3*"]
|===
| almacenamiento iSCSI | Parámetro | Límite 


.4+| *LUN* | Máximo por nodo | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamaño máximo | 16 TB 


| Máximo por volumen | 512 


| *igroups* | Máximo por nodo | 256 


.2+| *Iniciadores* | Máximo por nodo | 512 


| Máximo por igroup | 128 


| *sesiones iSCSI* | Máximo por nodo | 1.024 


.2+| *LIF* | Máximo por puerto | 1 


| Máximo por conjunto de puertos | 32 


| *portset* | Máximo por nodo | 256 
|===


[[cloud-volumes-ontap-ha-pairs-do-not-support-immediate-storage-giveback]]
== Los pares de Cloud Volumes ONTAP HA no admiten la devolución inmediata de almacenamiento

Después de que un nodo se reinicia, el partner debe sincronizar los datos antes de poder devolver el almacenamiento. El tiempo que tarda en resincronizar los datos depende de la cantidad de datos escritos por los clientes mientras el nodo estaba inactivo y de la velocidad de escritura de datos durante el tiempo de devolución.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Aprende cómo funciona el almacenamiento en un sistema de parejas de alta disponibilidad Cloud Volumes ONTAP que se ejecuta en Google Cloud"^].
