---
sidebar: sidebar 
permalink: task-getting-started-gcp.html 
keywords: google cloud platform, gcp, cloud manager, deploy the Console, launch the Console, create the Console, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, cloud backup, storage access key, gcp role, role, iam role, permissions, gcp permissions, cloud backup, the Console 
summary: Comience a utilizar Cloud Volumes ONTAP para Google Cloud en unos pocos pasos. 
---
= Descripción general de la implementación de Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para implementar Cloud Volumes ONTAP, primero necesitas conocer tu suscripción de Google Cloud y las licencias de Cloud Volumes ONTAP. También debes verificar que tienes un agente de NetApp Console creado para tu proyecto y organización de Google Cloud. Gran parte de la información de este tema debe realizarse como parte de la configuración de tu Console antes de empezar siquiera a implementar Cloud Volumes ONTAP.

[cols="20,35,25,25"]
|===
| Tarea | Descripción | Referencia | Notas para implementaciones en modo privado 


 a| 
Crear un agente de Console
 a| 
Si aún no tienes un agente de consola, crea uno antes de implementar Cloud Volumes ONTAP. Si implementas en una subred sin acceso a internet, instala manualmente el agente de consola y accede a la consola de NetApp que se ejecuta en ese agente.
 a| 
Consulta la guía de configuración de la consola: https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html["Crear un agente de Console en Google Cloud"^]
 a| 
Si la implementación se realiza en una subred sin acceso a internet, instala manualmente el agente de la consola y accede a la interfaz de usuario de la consola de NetApp que se ejecuta en ese agente de consola. Consulta la guía de configuración de la consola: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Instala manualmente el agente de la consola sin conexión a internet"^]



 a| 
Planifique su configuración
 a| 
La consola ofrece paquetes preconfigurados que se adaptan a los requisitos de su carga de trabajo, o puede crear su propia configuración.  Si elige su propia configuración, debe comprender las opciones disponibles.
 a| 
link:task-planning-your-config-gcp.html["Planifique su configuración"]
 a| 
Debes tener en cuenta aspectos de planificación similares para las implementaciones en modo privado.



 a| 
Configura tu red
 a| 
. Asegúrese de que su VPC y sus subredes admitan la conectividad entre el agente de la consola y Cloud Volumes ONTAP.
. Si planeas habilitar el data tiering, configura la subred de Cloud Volumes ONTAP para Private Google Access.
. Si está implementando un par de alta disponibilidad, asegúrese de tener cuatro VPC, cada una con su propia subred.
. Si está utilizando una VPC compartida, proporcione el rol _Usuario de red de cómputo_ a la cuenta de servicio del agente de consola.
. Habilite el acceso a Internet saliente desde la VPC de destino para NetApp AutoSupport.

 a| 
Consulta:

* link:reference-networking-gcp.html["Requisitos de red para Google Cloud"]
* Consulta la documentación de Google Cloud: https://cloud.google.com/vpc/docs/configure-private-google-access["Configura el acceso privado a Google"^]

 a| 
No es necesario que AutoSupport disponga de acceso a internet de salida. El resto de requisitos de red no sufren cambios.



 a| 
Configura una cuenta de servicio
 a| 
Cloud Volumes ONTAP requiere una cuenta de servicio de Google Cloud para habilitar la organización de datos por niveles y así trasladar los datos inactivos a almacenamiento de objetos de bajo coste en Google Cloud, y también para habilitar NetApp Backup and recovery para hacer copias de seguridad de los volúmenes en almacenamiento de objetos de bajo coste.
 a| 
* link:task-creating-gcp-service-account.html["Configura una cuenta de servicio"]
* link:concept-data-tiering.html["Conoce la organización por niveles de datos"]
* Consulta la https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery documentos"^]

 a| 
No hay consideraciones adicionales para las implementaciones en modo privado.



 a| 
Habilita las API de Google Cloud
 a| 
Activa las API de Google Cloud necesarias en tu proyecto. Es posible que ya las hayas activado al crear el agente de la Consola.
 a| 
Consulta la documentación de Google Cloud: https://cloud.google.com/apis/docs/getting-started#enabling_apis["Habilita las API de Google Cloud"^]
 a| 
Las API deben estar habilitadas. Ponte en contacto con tu administrador del cloud para habilitar las API necesarias en tu entorno privado.



 a| 
Implementa Cloud Volumes ONTAP desde la consola
 a| 
Cuando hayas realizado todos los requisitos previos, puedes completar los pasos del asistente para implementar Cloud Volumes ONTAP en Google Cloud.
 a| 
Consulta:

* link:task-quick-deploy-gcp.html["Implementa Cloud Volumes ONTAP con Quick create"]
* link:task-deploying-gcp.html["Implementa Cloud Volumes ONTAP usando opciones avanzadas"]

 a| 
Antes de iniciar la implementación, asegúrate de haber adquirido una licencia de Cloud Volumes ONTAP en NetApp. Las implementaciones en modo privado requieren licencias BYOL basadas en nodos. Las suscripciones de Marketplace no son compatibles para la facturación del uso de Cloud Volumes ONTAP. Obtén el archivo de licencia en NetApp y súbelo durante la implementación. Consulta:

* link:concept-license-management.html["Gestión de licencias para BYOL basado en nodos"]
* link:task-manage-node-licenses.html["Gestiona licencias BYOL basadas en nodos"]
* link:task-quick-deploy-gcp.html["Implementa Cloud Volumes ONTAP con Quick create"]
* link:task-deploying-gcp.html["Implementa Cloud Volumes ONTAP usando opciones avanzadas"]


|===
.Enlaces relacionados
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Creación de un agente de consola"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Instalación del software del agente de consola en un host Linux"^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Permisos de Google Cloud para el agente de la consola"^]

