---
sidebar: sidebar 
permalink: task-manage-svm-dr.html 
keywords: storage virtual machine, vserver, svm, storage vm, svm dr, disaster recovery, svm disaster recovery, storage vm dr 
summary: La NetApp Console no ​​proporciona ningún tipo de soporte de configuración u orquestación para la recuperación ante desastres de máquinas virtuales de almacenamiento.  Debe utilizar el Administrador del sistema o la CLI. 
---
= Configurar la recuperación ante desastres de la máquina virtual de almacenamiento para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console no ​​ofrece soporte de configuración u orquestación para la recuperación ante desastres de máquinas virtuales de almacenamiento (SVM).  Para realizar estas tareas, utilice el Administrador del sistema ONTAP o la CLI de ONTAP .

Si configuras la replicación de SnapMirror SVM entre dos sistemas Cloud Volumes ONTAP, la replicación debe ser entre dos sistemas en pareja de alta disponibilidad o dos sistemas de un solo nodo. No puedes configurar la replicación de SnapMirror SVM entre una pareja de alta disponibilidad y un sistema de un solo nodo.

Consulte los siguientes documentos para obtener las instrucciones de la CLI de ONTAP .

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guía rápida de preparación para la recuperación ante desastres de SVM"^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guía rápida de recuperación ante desastres de SVM"^]

