---
sidebar: sidebar 
permalink: task-file-verification-linux.html 
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, Linux 
summary: Verifique la firma de un archivo VHD exportado a través de la herramienta de archivo de resumen de imagen de Cloud Volumes ONTAP en Linux 
---
= Verificar la firma de la imagen de Azure Marketplace para Cloud Volumes ONTAP en Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La verificación de la firma de un archivo VHD exportado en Linux incluye validar la cadena de confianza, editar el archivo y verificar la firma.

.Pasos
. Descargue el archivo de imagen de Azure desde https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] y extraiga el archivo de resumen (.sig), el archivo de certificado de clave pública (.pem) y el archivo de certificado de cadena (.pem).
+
Referirse a https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html["Descargar el archivo de resumen de imagen de Azure"^] Para más información.

. Verificar la cadena de confianza.
+
[source, cli]
----
% openssl verify -CAfile Certificate-Chain-9.15.0P1_azure.pem Certificate-9.15.0P1_azure.pem
Certificate-9.15.0P1_azure.pem: OK
----
. Elimine 1 MB (1.048.576 bytes) al principio y 512 bytes al final del archivo VHD.  Al utilizar `tail` , el `-c +K` La opción genera bytes a partir del byte K del archivo.  Por lo tanto, pasa 1048577 a `tail -c` .
+
[source, cli]
----
% tail -c +1048577 ./9150.01000024.05090105.vhd > ./sign.tmp.tail
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----
. Utilice OpenSSL para extraer la clave pública del certificado y verificar el archivo eliminado (sign.tmp) con el archivo de firma y la clave pública.
+
El símbolo del sistema muestra mensajes que indican el éxito o el fracaso según la verificación.

+
[source, cli]
----
% openssl x509 -pubkey -noout -in ./Certificate-9.15.0P1_azure.pem > ./Code-Sign-Cert-Public-key.pub

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verification OK

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----
. Limpiar el espacio de trabajo.
+
[source, cli]
----
% rm ./9150.01000024.05090105.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----

