---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: AutoSupport supervisa de forma proactiva el estado de su sistema y envía mensajes al soporte técnico de NetApp .  De forma predeterminada, AutoSupport está habilitado en cada nodo para enviar mensajes al soporte técnico mediante el protocolo de transporte HTTPS.  Es mejor verificar que AutoSupport pueda enviar estos mensajes. 
---
= Verificar la configuración de AutoSupport para Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport supervisa de forma proactiva el estado de su sistema y envía mensajes al soporte técnico de NetApp .  De forma predeterminada, AutoSupport está habilitado en cada nodo para enviar mensajes al soporte técnico mediante el protocolo de transporte HTTPS.  Es mejor verificar que AutoSupport pueda enviar estos mensajes.

El único paso de configuración necesario es garantizar que Cloud Volumes ONTAP tenga conectividad a Internet saliente.  Para obtener más detalles, consulte los requisitos de red de su proveedor de nube.



== Requisitos de AutoSupport

Los nodos de Cloud Volumes ONTAP requieren acceso a Internet saliente para NetApp AutoSupport, que monitorea de forma proactiva el estado de su sistema y envía mensajes al soporte técnico de NetApp .

Las políticas de enrutamiento y firewall deben permitir el tráfico HTTPS a los siguientes puntos finales para que Cloud Volumes ONTAP pueda enviar mensajes de AutoSupport :

* \ https://mysupport.netapp.com/aods/asupmessage
* \ https://mysupport.netapp.com/asupprod/post/1.0/postAsup


Si no hay una conexión a Internet saliente disponible para enviar mensajes de AutoSupport , la NetApp Console configura automáticamente sus sistemas Cloud Volumes ONTAP para usar el agente de la consola como servidor proxy.  El único requisito es garantizar que el grupo de seguridad del agente de la consola permita conexiones _entrantes_ a través del puerto 3128. Necesitará abrir este puerto después de implementar el agente de consola.

Si definió reglas de salida estrictas para Cloud Volumes ONTAP, también deberá asegurarse de que el grupo de seguridad de Cloud Volumes ONTAP permita conexiones _salientes_ a través del puerto 3128.


TIP: Si está utilizando un par HA, el mediador HA no requiere acceso a Internet saliente.

Una vez que haya verificado que el acceso a Internet saliente está disponible, puede probar AutoSupport para asegurarse de que pueda enviar mensajes.  Para obtener instrucciones, consulte la https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["Documentación de ONTAP : Configurar AutoSupport"^] .



== Solucione los problemas de configuración de AutoSupport

Si no hay una conexión saliente disponible y la consola no puede configurar su sistema Cloud Volumes ONTAP para usar el agente de la consola como servidor proxy, recibirá una notificación de la consola indicando que su sistema no puede enviar mensajes de AutoSupport . Siga estos pasos para solucionar este problema.

.Pasos
. Conéctese de forma segura (usando SSH) al sistema Cloud Volumes ONTAP para usar la CLI de ONTAP .
+
link:task-connecting-to-otc.html["Aprenda a usar SSH en Cloud Volumes ONTAP"] .

. Verifique el estado detallado del subsistema AutoSupport :
+
`autosupport check show-details`

+
La respuesta se ve así:

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
Si el estado de la categoría http-https es `OK` significa que AutoSupport está configurado correctamente y se pueden enviar mensajes.

. De lo contrario, verifique la URL del proxy para cada nodo de Cloud Volumes ONTAP :
+
`autosupport show -fields proxy-url`

. Si el parámetro URL del proxy está vacío, configure Cloud Volumes ONTAP para usar el agente de la consola como proxy:
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`

. Verifique nuevamente el estado de AutoSupport :
+
`autosupport check show-details`

. Si el estado sigue siendo fallido, valide que haya conectividad entre Cloud Volumes ONTAP y el agente de la consola a través del puerto `3128`.
. Si el estado sigue siendo fallido después de la verificación, acceda por SSH al agente de la consola.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm["Obtenga más información sobre cómo conectarse a la máquina virtual Linux para el agente de consola"^]

. Ir a `/opt/application/netapp/cloudmanager/docker_occm/data/`.
. Abra el archivo de configuración del proxy `squid.conf`. Esta es la estructura del archivo:
+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
. Si su archivo no tiene una entrada para el bloque CIDR del sistema Cloud Volumes ONTAP , agregue una nueva entrada y permita el acceso:
+
`acl cvonet src <cidr>`

+
`http_access allow cvonet`

+
He aquí un ejemplo:

+
[listing]
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----
. Después de editar el archivo de configuración, reinicie el contenedor proxy como `sudo`. Luego, dependiendo de si estás usando Docker o Podman, ejecuta estos comandos:
+
Para Docker, ejecute `docker restart squid`.

+
Si está utilizando Podman, ejecute `podman restart squid`.

. Regrese a la CLI de ONTAP y verifique que Cloud Volumes ONTAP pueda enviar mensajes de AutoSupport :
+
`autosupport check show-details`



.Enlaces relacionados
* link:reference-networking-aws.html["Requisitos de red para Cloud Volumes ONTAP en AWS"^]
* link:reference-networking-azure.html["Requisitos de red para Cloud Volumes ONTAP en Azure"^]
* link:reference-networking-gcp.html["Requisitos de red para Cloud Volumes ONTAP en Google Cloud"^]

