---
sidebar: sidebar 
permalink: task-modify-write-speed.html 
keywords: write speed, high write speed, normal write speed, change write speed 
summary: Es posible que necesite cambiar la configuración de los sistemas Cloud Volumes ONTAP a medida que cambien sus necesidades de almacenamiento.  Por ejemplo, puede cambiar entre configuraciones de pago por uso, cambiar la instancia o el tipo de VM, y más. 
---
= Modificar la velocidad de escritura del sistema
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede elegir una velocidad de escritura normal o alta para Cloud Volumes ONTAP en la consola de NetApp .  La velocidad de escritura predeterminada es normal.  Puede cambiar a alta velocidad de escritura si su carga de trabajo requiere un rendimiento de escritura rápido.

La alta velocidad de escritura es compatible con todos los tipos de sistemas de nodo único y algunas configuraciones de par HA.  Ver configuraciones admitidas en el https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/["Notas de la versión de Cloud Volumes ONTAP"^]

Antes de cambiar la velocidad de escritura, debelink:concept-write-speed.html["Comprender las diferencias entre la configuración normal y la alta"] .

.Acerca de esta tarea
* Asegúrese de que operaciones como la creación de volumen o agregados no estén en curso.
* Tenga en cuenta que este cambio reinicia el sistema Cloud Volumes ONTAP .  Este es un proceso disruptivo que requiere tiempo de inactividad para todo el sistema.


.Pasos
. En la página *Sistemas*, haga doble clic en el nombre del sistema que configura para la velocidad de escritura.
. En la pestaña Descripción general, haga clic en el panel Características y luego haga clic en el ícono de lápiz junto a *Velocidad de escritura*.
. Seleccione *Normal* o *Alto*.
+
Si elige Alto, deberá leer la declaración "Entiendo..." y confirmar marcando la casilla.

+

NOTE: La opción de velocidad de escritura *Alta* es compatible con pares Cloud Volumes ONTAP HA en Google Cloud a partir de la versión 9.13.0.

. Haga clic en *Guardar*, revise el mensaje de confirmación y luego haga clic en *Aprobar*.

