---
sidebar: sidebar 
permalink: task-getting-started-aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console 
summary: Comprueba que has cumplido todos los requisitos previos para implementar Cloud Volumes ONTAP en AWS. 
---
= Descripción general de la implementación de Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para implementar Cloud Volumes ONTAP, primero debes conocer los detalles de tu suscripción a AWS y las licencias de Cloud Volumes ONTAP. También debes comprobar que tienes un agente de la consola de NetApp creado para tu cuenta de AWS. Gran parte de la información de este tema debe llevarse a cabo como parte de la configuración de la consola antes incluso de comenzar a implementar Cloud Volumes ONTAP.

[cols="20,35,25,25"]
|===
| Tarea | Descripción | Referencia | Notas para implementaciones en modo privado 


 a| 
Crear un agente de Console
 a| 
Si aún no tienes un agente de consola, crea uno antes de implementar Cloud Volumes ONTAP. Si implementas en una subred sin acceso a internet, instala manualmente el agente de consola y accede a la consola de NetApp que se ejecuta en ese agente.
 a| 
Consulta la guía de configuración de la consola: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["Crear un agente de Console en AWS"^]
 a| 
Si la implementación se realiza en una subred sin acceso a internet, instala manualmente el agente de la consola y accede a la interfaz de usuario de la consola de NetApp que se ejecuta en ese agente de consola. Consulta la guía de configuración de la consola: https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Instala manualmente el agente de la consola sin conexión a internet"^]



 a| 
Planifique su configuración
 a| 
La consola ofrece paquetes preconfigurados que se adaptan a los requisitos de su carga de trabajo, o puede crear su propia configuración.  Si elige su propia configuración, debe comprender las opciones disponibles.
 a| 
link:task-planning-your-config.html["Planifique su configuración"]
 a| 
Debes tener en cuenta aspectos de planificación similares para las implementaciones en modo privado.



 a| 
Configura tu red
 a| 
. Asegúrate de que tu VPC y tus subredes admitan la conectividad entre el agente de la consola y Cloud Volumes ONTAP.
. Activa el acceso a Internet saliente para AutoSupport.
. Configura un punto de conexión de VPC a Amazon S3 para la organización de datos por niveles. Se requiere un punto de conexión de VPC si quieres organizar los datos inactivos de Cloud Volumes ONTAP en almacenamiento de objetos de bajo coste.

 a| 
link:reference-networking-aws.html["Requisitos de red para AWS"]
 a| 
No es necesario que AutoSupport disponga de acceso a internet de salida. El resto de requisitos de red no sufren cambios.



 a| 
Configurar AWS KMS
 a| 
Si deseas utilizar el cifrado de Amazon con Cloud Volumes ONTAP, asegúrate de que exista una clave maestra de cliente (CMK) activa y modifica la política de claves para añadir el rol de IAM del agente de la Console como usuario de la clave.
 a| 
link:task-setting-up-kms.html["Configurar AWS KMS"]
 a| 
Se aplican pasos similares a las implementaciones en modo privado.



 a| 
Implementa Cloud Volumes ONTAP desde la consola
 a| 
Una vez que hayas cumplido todos los requisitos previos, podrás seguir los pasos del asistente para implementar Cloud Volumes ONTAP en AWS.
 a| 
* link:task-quick-deploy-aws.html["Implementa Cloud Volumes ONTAP con Quick create"]
* link:task-deploying-otc-aws.html["Implementa Cloud Volumes ONTAP usando opciones avanzadas"]

 a| 
Antes de iniciar la implementación, asegúrate de haber adquirido una licencia de Cloud Volumes ONTAP en NetApp. Las implementaciones en modo privado requieren licencias BYOL basadas en nodos. Las suscripciones de Marketplace no son compatibles para la facturación del uso de Cloud Volumes ONTAP. Obtén el archivo de licencia en NetApp y súbelo durante la implementación. Consulta:

* link:concept-license-management.html["Gestión de licencias para BYOL basado en nodos"]
* link:task-manage-node-licenses.html["Gestiona licencias BYOL basadas en nodos"]
* link:task-quick-deploy-aws.html["Implementa Cloud Volumes ONTAP con Quick create"]
* link:task-deploying-otc-aws.html["Implementa Cloud Volumes ONTAP usando opciones avanzadas"]


|===
.Enlaces relacionados
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["Crear un agente de consola para AWS"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["Cree un agente de consola desde AWS Marketplace"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Instalar y configurar un agente de consola local"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["Permisos de AWS para el agente de consola"^]

