= Fin de la disponibilidad de las licencias basadas en nodos
:allow-uri-read: 




=== Fin de la disponibilidad de las licencias basadas en nodos

NetApp ha planificado el fin de la disponibilidad (EOA) y el fin del soporte (EOS) de las licencias basadas en nodos de Cloud Volumes ONTAP .  A partir del 11 de noviembre de 2024, se finalizará la disponibilidad limitada de licencias basadas en nodos. El soporte para licencias basadas en nodos finaliza el 31 de diciembre de 2024.  Después del fin de su licencia basada en nodos, debe realizar la transición a una licencia basada en capacidad mediante la herramienta de conversión de licencias BlueXP .

Para compromisos anuales o de largo plazo, NetApp recomienda que se comunique con su representante de NetApp antes de la fecha de EOA o la fecha de vencimiento de la licencia para asegurarse de que se cumplan los requisitos previos para la transición.  Si no tiene un contrato a largo plazo para un nodo de Cloud Volumes ONTAP y ejecuta su sistema con una suscripción de pago por uso (PAYGO) a pedido, es importante planificar su conversión antes de la fecha de finalización del servicio.  Tanto para contratos a largo plazo como para suscripciones PAYGO, puede utilizar la herramienta de conversión de licencias de BlueXP para una conversión sin problemas.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Fin de la disponibilidad de las licencias basadas en nodos"^] https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-convert-node-capacity.html["Convertir una licencia basada en nodos de Cloud Volumes ONTAP a una licencia basada en capacidad"^]



=== Eliminación de implementaciones basadas en nodos de BlueXP

La opción de implementar sistemas Cloud Volumes ONTAP mediante licencias basadas en nodos está obsoleta en BlueXP.  Salvo algunos casos especiales, no se pueden utilizar licencias basadas en nodos para implementaciones de Cloud Volumes ONTAP para ningún proveedor de nube.

NetApp reconoce los siguientes requisitos de licencia únicos en cumplimiento con las obligaciones contractuales y las necesidades operativas, y continuará respaldando las licencias basadas en nodos en estas situaciones:

* Clientes del sector público de EE. UU.
* Despliegues en modo privado
* Implementaciones de Cloud Volumes ONTAP en AWS en la región de China
* Si tiene un by-node válido y no vencido, traiga su propia licencia (licencia BYOL)


https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Fin de la disponibilidad de las licencias basadas en nodos"^]



=== Adición de un nivel frío para datos de Cloud Volumes ONTAP en el almacenamiento de blobs de Azure

BlueXP ahora le permite seleccionar un nivel frío para almacenar los datos del nivel de capacidad inactivo en el almacenamiento de blobs de Azure.  Agregar el nivel frío a los niveles frío y caliente existentes le brinda una opción de almacenamiento más asequible y una mejor eficiencia de costos.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html#data-tiering-in-azure["Organización de datos en niveles en Azure"^]



=== Opción para restringir el acceso público a la cuenta de almacenamiento de Azure

Ahora tiene la opción de restringir el acceso público a su cuenta de almacenamiento para los sistemas Cloud Volumes ONTAP en Azure.  Al deshabilitar el acceso, puede proteger su dirección IP privada contra exposición incluso dentro de la misma VNet, en caso de que sea necesario cumplir con las políticas de seguridad de su organización.  Esta opción también deshabilita la clasificación de datos para sus sistemas Cloud Volumes ONTAP y es aplicable tanto a pares de nodos únicos como a pares de alta disponibilidad.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html#security-group-rules["Reglas del grupo de seguridad"^] .



=== Habilitación de WORM después de implementar Cloud Volumes ONTAP

Ahora tiene la posibilidad de activar el almacenamiento de escritura única y lectura múltiple (WORM) en un sistema Cloud Volumes ONTAP existente usando BlueXP.  Esta funcionalidad le proporciona la flexibilidad de habilitar WORM en un entorno de trabajo, incluso si WORM no estaba habilitado en él durante su creación.  Una vez habilitado, no podrás deshabilitar WORM.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html#enabling-worm-on-a-cloud-volumes-ontap-working-environment["Habilitación de WORM en un entorno de trabajo de Cloud Volumes ONTAP"^]
