= Capacidad para mejorar el rendimiento de los discos SSD Premium v2 en Azure
:allow-uri-read: 




[[ability-to-enhance-performance-of-premium-ssd-v2-disks-in-azure]]
=== Capacidad para mejorar el rendimiento de los discos SSD Premium v2 en Azure

Ahora puede mejorar el rendimiento de los discos administrados SSD Premium v2 en Azure modificando los parámetros de IOPS y rendimiento.  Al utilizar esta capacidad, puede optimizar el rendimiento de almacenamiento de sus sistemas en función de los requisitos de su carga de trabajo.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-perf-params-azure.html["Administrar el rendimiento de los discos SSD v2 Premium para Cloud Volumes ONTAP en Azure"^].



[[overage-charging-for-essentials-licenses-simplified]]
=== Cobro por exceso de licencias Essentials simplificado

En el caso de los contratos anuales y las ofertas privadas de Cloud Volumes ONTAP en el marketplace, el cálculo de los excesos de uso de las licencias Essentials ahora se ajusta a los paquetes Bring-Your-Own License (BYOL). Antes, los excesos de uso se facturaban según las tarifas por hora del marketplace correspondientes al paquete Essentials exacto. Ahora, si tu contrato anual del marketplace incluye varios paquetes Essentials, la NetApp Console cobra los excesos de un paquete Essentials en función de la capacidad disponible del paquete Essentials de mayor precio incluido en tu suscripción. Esto simplifica los cálculos de exceso para los paquetes Essentials y asegura una transición fluida del modelo de licencia BYOL a un modelo basado en suscripción.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Cómo se cobran los excedentes de las licencias Essentials"^]



[[support-for-azure-edsv6-sizes-series]]
=== Compatibilidad con la serie de tamaños de Azure Edsv6

A partir de Cloud Volumes ONTAP 9.17.1, puede implementar máquinas virtuales de la serie Azure Edsv6 a través de la NetApp Console para nuevas instancias de Cloud Volumes ONTAP .  Cloud Volumes ONTAP 9.17.1 y versiones posteriores solo admitirán máquinas virtuales de segunda generación para nuevas implementaciones.  Estas máquinas de segunda generación son compatibles con las últimas tecnologías, como la Interfaz de firmware extensible unificada (UEFI), los sistemas Azure Boost y NVMe.  Son ideales para sistemas y aplicaciones que hacen un uso intensivo de la memoria y que necesitan almacenamiento local rápido, como servidores de bases de datos y motores de análisis.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Configuraciones compatibles con Cloud Volumes ONTAP en Azure"^]
