= Autenticación de usuario habilitada para acceder al Administrador del sistema desde BlueXP
:allow-uri-read: 




[[user-authentication-enabled-for-accessing-system-manager-from-bluexp]]
=== Autenticación de usuario habilitada para acceder al Administrador del sistema desde BlueXP

Como administrador de BlueXP , ahora puede activar la autenticación para los usuarios de ONTAP que acceden a ONTAP System Manager desde BlueXP.  Puede habilitar esta opción editando la configuración del conector BlueXP .  Esta opción está disponible para los modos estándar y privado.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-administer-advanced-view.html["Administrar Cloud Volumes ONTAP mediante el Administrador del sistema"^].



[[bluexp-advanced-view-renamed-to-system-manager]]
=== La Vista avanzada de BlueXP ahora se llama Administrador del sistema

La opción para la gestión avanzada de Cloud Volumes ONTAP desde BlueXP a través de ONTAP System Manager ha cambiado de nombre de *Vista avanzada* a *Administrador del sistema*.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-administer-advanced-view.html["Administrar Cloud Volumes ONTAP mediante el Administrador del sistema"^].



[[introducing-a-simpler-way-to-manage-licenses-with-the-bluexp-digital-wallet]]
=== Presentamos una forma más sencilla de administrar licencias con la BlueXP digital wallet

Ahora, puede experimentar una gestión simplificada de las licencias de Cloud Volumes ONTAP mediante el uso de puntos de navegación mejorados dentro de la BlueXP digital wallet:

* Acceda fácilmente a la información de su licencia de Cloud Volumes ONTAP a través de las pestañas *Administración > Licenses and subscriptions > Descripción general/Licencias directas*.
* Selecciona *Ver* en el panel Cloud Volumes ONTAP de la pestaña *Resumen* para obtener una visión completa de tus licencias basadas en capacidad. Esta vista avanzada ofrece información detallada sobre tus licencias y suscripciones.
* Si prefieres la interfaz anterior, puedes seleccionar el botón *Switch to legacy view* para ver los detalles de las licencias por tipo y modificar los métodos de cobro de tus licencias.


link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["Administrar licencias basadas en capacidad"^].
